name = "GeneralizedEigenvalueMinimization"
uuid = "07676b6a-b759-46e4-8c95-189815504c5c"
authors = ["Zdeněk Hurák <hurak@fel.cvut.cz>"]
version = "0.1.0"

[deps]
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"

[compat]
Convex = "0.14"
SCS = "0.7, 0.8"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
